/* SpeakUp trains intelligibility and leadership delivery, never accent erasure. */
const Curriculum = {
  skills: [
    { id: 'v-w', name: 'V / W contrast', category: 'Consonant contrast', cue: 'For V, touch lower lip to upper teeth. For W, round both lips without friction.', visualCue: 'Watch the lower lip move to the teeth for V; keep both lips rounded for W.', videoUrl: 'https://www.youtube.com/watch?v=jTcfSBy_XWo', items: [['very', '/ˈver.i/', 'We verified the value.'], ['work', '/wɜːk/', 'The work is ready for review.']] },
    { id: 'th-voiced', name: 'Voiced TH', category: 'Consonant contrast', cue: 'Let the tongue tip show lightly and keep your voice on for TH in “this”.', visualCue: 'Use a close-up guide for a light visible tongue tip; the camera never judges hidden tongue position.', videoUrl: 'https://www.youtube.com/watch?v=YNQeG_sWDkM', items: [['this', '/ðɪs/', 'This is the third version.'], ['those', '/ðəʊz/', 'Those changes look good.']] },
    { id: 'th-voiceless', name: 'Unvoiced TH', category: 'Consonant contrast', cue: 'Let air pass over a light tongue-tip contact for TH in “think”.', visualCue: 'The useful visual is a small visible tongue tip plus steady airflow, not a tongue score.', videoUrl: 'https://www.youtube.com/watch?v=1Tor0LDdVKY', items: [['think', '/θɪŋk/', 'I think the path is clear.'], ['three', '/θriː/', 'We have three options.']] },
    { id: 'r-l', name: 'R / L clarity', category: 'Consonant contrast', cue: 'For R, avoid touching the tooth ridge; for L, make one light tongue-tip contact.', visualCue: 'Compare rounded R lips with a relaxed L mouth. Use the video for the hidden tongue contact.', videoUrl: 'https://www.youtube.com/watch?v=TjwZPtjtGJg', items: [['really', '/ˈrɪə.li/', 'We really need reliable logs.'], ['release', '/rɪˈliːs/', 'The release is ready.']] },
    { id: 'final-consonants', name: 'Final consonants', category: 'Word endings', cue: 'Finish the last sound; do not add an extra vowel after the word.', visualCue: 'Keep the final jaw and lip movement small but complete, then pause.', videoUrl: 'https://www.youtube.com/watch?v=jTcfSBy_XWo', items: [['project', '/ˈprɒdʒekt/', 'The project shipped last week.'], ['build', '/bɪld/', 'The build passed.']] },
    { id: 'vowels', name: 'Core vowels', category: 'Vowel clarity', cue: 'Hold the vowel clearly before moving into the final consonant.', visualCue: 'Use the camera only for visible jaw opening and lip rounding.', videoUrl: 'https://www.youtube.com/results?search_query=English+vowel+mouth+position+pronunciation', items: [['work', '/wɜːk/', 'The work is ready for review.'], ['world', '/wɜːld/', 'The world is changing quickly.']] },
    { id: 'stress', name: 'Word stress', category: 'Prosody', cue: 'Make the stressed syllable longer and clearer, not simply louder.', visualCue: 'Notice the longer jaw movement on the important syllable.', videoUrl: 'https://www.youtube.com/results?search_query=English+word+stress+pronunciation+practice', items: [['responsibility', '/rɪˌspɒnsəˈbɪləti/', 'I will take responsibility for the rollout.'], ['communication', '/kəˌmjuːnɪˈkeɪʃən/', 'Clear communication reduces risk.']] },
    { id: 'rhythm', name: 'Sentence rhythm', category: 'Prosody', cue: 'Stress the key information and make connecting words lighter.', visualCue: 'Use recording length and pauses as evidence; lip shape is secondary here.', videoUrl: 'https://www.youtube.com/results?search_query=English+sentence+rhythm+connected+speech+practice', items: [['update', '/ʌpˈdeɪt/', 'Here is a short update on the incident.'], ['priority', '/praɪˈɒrəti/', 'Our priority is customer impact.']] },
    { id: 'clarity', name: 'Technical clarity', category: 'Career transfer', cue: 'Use one idea per sentence, then pause before your key point.', visualCue: 'A steady head and relaxed jaw support clear, calm delivery.', videoUrl: 'https://www.youtube.com/results?search_query=English+technical+presentation+pronunciation+clarity', items: [['architecture', '/ˈɑːkɪtektʃə/', 'I recommend a simpler architecture.'], ['trade-off', '/ˈtreɪd ɒf/', 'The trade-off is speed versus reliability.']] },
    { id: 'leadership', name: 'Leadership presence', category: 'Career transfer', cue: 'Deliver the decision calmly, with emphasis on the outcome and next step.', visualCue: 'Look into the camera and leave a small pause before the decision.', videoUrl: 'https://www.youtube.com/results?search_query=English+leadership+communication+intonation+practice', items: [['decision', '/dɪˈsɪʒən/', 'I disagree, but I support the decision.'], ['alignment', '/əˈlaɪnmənt/', 'Let us confirm alignment before we proceed.']] }
  ],
  perceptionPairs: [
    { skillId: 'r-l', listenWord: 'right', options: ['right', 'light'], answer: 'right' }, { skillId: 'v-w', listenWord: 'west', options: ['vest', 'west'], answer: 'west' }, { skillId: 'th-voiceless', listenWord: 'three', options: ['three', 'free'], answer: 'three' }, { skillId: 'final-consonants', listenWord: 'build', options: ['build', 'bill'], answer: 'build' }, { skillId: 'stress', listenWord: 'communication', options: ['COMmunication', 'communiCAtion'], answer: 'communiCAtion' }
  ],
  skill(id) { return this.skills.find(skill => skill.id === id); },
  listeningItem(pair, stage = 'Hear the contrast') { const skill = this.skill(pair.skillId); return { id: `listen-${pair.skillId}-${pair.listenWord}`, kind: 'listening', skillId: pair.skillId, target: pair.options.join(' / '), listenWord: pair.listenWord, options: pair.options, answer: pair.answer, format: 'Listening', stage, category: skill.category, cue: skill.cue, visualCue: skill.visualCue, videoUrl: skill.videoUrl }; },
  diagnosticPlan() { const listening = this.perceptionPairs.map(pair => this.listeningItem(pair, 'Diagnostic · hear')); const ids = ['v-w', 'th-voiceless', 'r-l', 'final-consonants', 'vowels', 'stress', 'rhythm']; return [...listening, ...ids.map((id, index) => this.createItem(this.skill(id), index, index > 4 ? 'Sentence' : 'Word', 'Diagnostic · say'))]; },
  progress(history, skillId) { const attempts = history.filter(item => item.skillId === skillId).sort((a, b) => a.timestamp - b.timestamp); const recentProduction = attempts.filter(item => item.format !== 'Listening').slice(-5); const clear = recentProduction.filter(item => item.score >= 82).length; const transfers = attempts.filter(item => item.format === 'Sentence' && item.score >= 82).length; const heard = attempts.filter(item => item.format === 'Listening' && item.score >= 82).length; const days = new Set(recentProduction.filter(item => item.score >= 82).map(item => item.date)).size; const retained = attempts.some(item => item.format !== 'Listening' && item.score >= 82 && Date.now() - item.timestamp > 6 * 86400000); const ready = clear >= 4 && transfers >= 1 && heard >= 2 && days >= 3 && retained; return { attempts, recentProduction, clear, transfers, heard, days, retained, ready, confidence: Math.min(100, clear * 12 + Math.min(transfers, 2) * 12 + Math.min(heard, 2) * 10 + Math.min(days, 3) * 10 + (retained ? 18 : 0)) }; },
  createItem(skill, index, format = 'Word', stage = 'Precision') { const [target, ipa, sentence] = skill.items[index % skill.items.length]; return { id: `${skill.id}-${format}-${target}`, skillId: skill.id, target, ipa, sentence, spokenTarget: format === 'Word' ? target : sentence, format, stage, cue: skill.cue, category: skill.category, visualCue: skill.visualCue, videoUrl: skill.videoUrl }; },
  rankSkills(history, profile) { const MandarinBias = ['r-l', 'v-w', 'th-voiceless', 'final-consonants', 'stress']; return this.skills.map(skill => ({ skill, progress: this.progress(history, skill.id), bias: ['Mandarin', 'Cantonese'].includes(profile.firstLanguage) ? MandarinBias.indexOf(skill.id) : 99 })).sort((a, b) => a.progress.confidence - b.progress.confidence || a.bias - b.bias || a.progress.attempts.length - b.progress.attempts.length); },
  todayPlan(history, profile) { const due = history.filter(item => item.nextReviewAt && item.nextReviewAt <= Date.now()).sort((a, b) => a.nextReviewAt - b.nextReviewAt); const ranked = this.rankSkills(history, profile), primary = ranked[0], secondary = ranked[1], items = []; due.slice(0, 2).forEach((attempt, index) => { const skill = this.skill(attempt.skillId) || primary.skill; items.push(this.createItem(skill, index, attempt.format === 'Word' ? 'Sentence' : 'Word', 'Review')); }); items.push(this.listeningItem(this.perceptionPairs.find(pair => pair.skillId === primary.skill.id) || this.perceptionPairs[0])); items.push(this.createItem(primary.skill, 0, 'Word', 'Shape + say')); items.push(this.createItem(primary.skill, 1, 'Sentence', 'Transfer')); items.push(this.createItem(secondary.skill, 0, 'Word', 'Maintenance')); items.push(this.createItem(this.skill('clarity'), 0, 'Sentence', 'Career lab')); return { items: items.slice(0, 6), title: `Build ${primary.skill.name}`, focus: `${primary.skill.cue} First hear it, then shape it, then use it in a work sentence.`, minutes: profile.dailyMinutes || 30, primary }; },
  nextLevel(history) { const core = this.skills.filter(skill => !['clarity', 'leadership'].includes(skill.id)); const ready = core.filter(skill => this.progress(history, skill.id).ready).length; return { ready, total: core.length, unlocked: ready === core.length }; }
};
